### ISSUE TITLE
yale hand not launching per the startup instructions

### ISSUE THREAD

**Issue by lucbettaieb** [cwru-robotics/cwru_baxter#1]
when I:
`roslaunch cwru_baxter_sim baxter_world.launch`

then:
`roslaunch cwru_baxter_sim cwru_baxter_sim.launch`

cwru_baxter_sim complains about there not being a yale hand model, since there isn't one.

What's the correct way to launch the sim so I can test it on the thumb drive I'm making?

**Comment by wsnewman** [comment]
Um...I'll have to look into that.  I need to clean things up.

However, the real crisis is that we need to get our students something to
work with for initial problem sets.  They won't need the Baxter simulator
for a while yet.

Do we (i.e. you) have a solution?  A drive that works on the Alienware
machines?  This needs to be the top priority.
(then we could ask them to git pull later to update baxter stuff)

On Tue, Sep 1, 2015 at 1:40 PM, Luc Bettaieb <notifications@github.com>
wrote:

> when I:
> roslaunch cwru_baxter_sim baxter_world.launch
>
> then:
> roslaunch cwru_baxter_sim cwru_baxter_sim.launch
>
> cwru_baxter_sim complains about there not being a yale hand model, since
> there isn't one.
>
> What's the correct way to launch the sim so I can test it on the thumb
> drive I'm making?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwru-robotics/cwru_baxter/issues/1>.
>



-- 
Wyatt Newman, Ph.D., P.E.
Professor, EECS Dept
Case Western Reserve University
Cleveland, OH 44106
216-368-6432
wyatt.newman@case.edu
