### ISSUE TITLE
Should all of the code that currently lives here actually live here?

### ISSUE THREAD

**Issue by lucbettaieb** [cwru-robotics/cwru_baxter#7]
Some of the code that isn't baxter-specific should perhaps be moved (later) to a generic 'development' repo.

**Comment by wsnewman** [comment]
which packages?

On Tue, Oct 27, 2015 at 9:09 AM, Luc Bettaieb <notifications@github.com>
wrote:

> Some of the code that isn't baxter-specific should perhaps be moved
> (later) to a generic 'development' repo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwru-robotics/cwru_baxter/issues/7>.
>



-- 
Wyatt Newman, Ph.D., P.E.
Professor, EECS Dept
Case Western Reserve University
Cleveland, OH 44106
216-368-6432
wyatt.newman@case.edu

**Comment by lucbettaieb** [comment]
Perhaps, and tell me if I'm wrong and they are indeed baxter-specific (but in that case, perhaps they could be generalized)
 - cartesian_moves
 - cwru_pcl_utils (move to cwru_vision when easy to do so?)
 - example_opencv (cwru_vision?)
 - example_tf_listener
 - interactive_marker_node
 - pcl_perception_node

**Comment by wsnewman** [comment]
ah...worthy of discussion.  example_opencv should move.
 example_tf_listener should move (probably already  obsolete relative to
eecs repo).  cwru_pcl_utils...I just started this one.  I guess it could
live in some perception repo.  Similarly, pcl_perception_node.

cartesian_moves might have Baxter-specific stuff...so maybe should be
renamed baxter_cartesian_moves.  (I'll have to check).

not sure if I made the interactive marker node baxter-specific.  I'll need
to poke into it, and possibly rename it if it's baxter specific.

Looks like we'll have to make the class clone yet another repo...or 2.

On Tue, Oct 27, 2015 at 11:12 AM, Luc Bettaieb <notifications@github.com>
wrote:

> Perhaps, and tell me if I'm wrong and they are indeed baxter-specific (but
> in that case, perhaps they could be generalized)
>
>    - cartesian_moves
>    - cwru_pcl_utils (move to cwru_vision when easy to do so?)
>    - example_opencv (cwru_vision?)
>    - example_tf_listener
>    - interactive_marker_node
>    - pcl_perception_node
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwru-robotics/cwru_baxter/issues/7#issuecomment-151536008>
> .
>



-- 
Wyatt Newman, Ph.D., P.E.
Professor, EECS Dept
Case Western Reserve University
Cleveland, OH 44106
216-368-6432
wyatt.newman@case.edu

**Comment by lucbettaieb** [comment]
I think this would be some good stuff to do, but after the class is finished so that it complicates things less.

**Comment by wsnewman** [comment]
sold

On Tue, Oct 27, 2015 at 11:48 AM, Luc Bettaieb <notifications@github.com>
wrote:

> I think this would be some good stuff to do, but after the class is
> finished so that it complicates things less.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cwru-robotics/cwru_baxter/issues/7#issuecomment-151547102>
> .
>



-- 
Wyatt Newman, Ph.D., P.E.
Professor, EECS Dept
Case Western Reserve University
Cleveland, OH 44106
216-368-6432
wyatt.newman@case.edu
